version: "3"
services:
  redis:
    image: redis:6.2
    container_name: hotel-redis
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis-data:/data"
  mysql:
    image: mysql:8.0
    container_name: hotel-mysql
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password

    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - "./docker/mysql-data:/var/lib/mysql"
