spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3308/hotel?characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.qq.com
    port: 465
    username: 2858712518@qq.com
    password: lzbticyvndvddecd
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
mybatis:
  type-aliases-package: org.example.springboot.entity
  mapper-locations: classpath:mapper/*.xml
server:
  url: http://localhost:8080

jwt:
  secret: your-256-bit-secret-long-string-here-with-at-least-32-characters-long
