spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3308/hotel?characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
mybatis:
  type-aliases-package: org.example.springboot.entity
  mapper-locations: classpath:mapper/*.xml
server:
  url: http://localhost:8080